/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppExpiryTrackerRouteImport } from './routes/_app/expiry-tracker'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppPermissionsRouteImport } from './routes/_app/permissions'
import { Route as AppPosRouteImport } from './routes/_app/pos'
import { Route as AppPrescriptionsRouteImport } from './routes/_app/prescriptions'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppSalesRouteImport } from './routes/_app/sales'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppStaffRouteImport } from './routes/_app/staff'
import { Route as AuthSignInRouteImport } from './routes/_auth.sign-in'
import { Route as AppCustomersIndexRouteImport } from './routes/_app/customers.index'
import { Route as AppCustomersBlacklistRouteImport } from './routes/_app/customers.blacklist'
import { Route as AppCustomersNewRouteImport } from './routes/_app/customers.new'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products.index'
import { Route as AppProductsNewRouteImport } from './routes/_app/products.new'
import { Route as AppSuppliersIndexRouteImport } from './routes/_app/suppliers.index'
import { Route as AppSuppliersNewRouteImport } from './routes/_app/suppliers.new'
import { Route as AppProductsProductIdIndexRouteImport } from './routes/_app/products.$productId.index'
import { Route as AppProductsProductIdEditRouteImport } from './routes/_app/products.$productId.edit'
import { Route as AppSuppliersSupplierIdEditRouteImport } from './routes/_app/suppliers.$supplierId.edit'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExpiryTrackerRoute = AppExpiryTrackerRouteImport.update({
  id: '/expiry-tracker',
  path: '/expiry-tracker',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPermissionsRoute = AppPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPrescriptionsRoute = AppPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCustomersBlacklistRoute = AppCustomersBlacklistRouteImport.update({
  id: '/customers/blacklist',
  path: '/customers/blacklist',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCustomersNewRoute = AppCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsNewRoute = AppProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSuppliersIndexRoute = AppSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSuppliersNewRoute = AppSuppliersNewRouteImport.update({
  id: '/suppliers/new',
  path: '/suppliers/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsProductIdIndexRoute =
  AppProductsProductIdIndexRouteImport.update({
    id: '/products/$productId/',
    path: '/products/$productId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppProductsProductIdEditRoute =
  AppProductsProductIdEditRouteImport.update({
    id: '/products/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppSuppliersSupplierIdEditRoute =
  AppSuppliersSupplierIdEditRouteImport.update({
    id: '/suppliers/$supplierId/edit',
    path: '/suppliers/$supplierId/edit',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/expiry-tracker': typeof AppExpiryTrackerRoute
  '/inventory': typeof AppInventoryRoute
  '/permissions': typeof AppPermissionsRoute
  '/pos': typeof AppPosRoute
  '/prescriptions': typeof AppPrescriptionsRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/sign-in': typeof AuthSignInRoute
  '/customers/blacklist': typeof AppCustomersBlacklistRoute
  '/customers/new': typeof AppCustomersNewRoute
  '/products/new': typeof AppProductsNewRoute
  '/suppliers/new': typeof AppSuppliersNewRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/products/': typeof AppProductsIndexRoute
  '/suppliers/': typeof AppSuppliersIndexRoute
  '/products/$productId/edit': typeof AppProductsProductIdEditRoute
  '/suppliers/$supplierId/edit': typeof AppSuppliersSupplierIdEditRoute
  '/products/$productId/': typeof AppProductsProductIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/expiry-tracker': typeof AppExpiryTrackerRoute
  '/inventory': typeof AppInventoryRoute
  '/permissions': typeof AppPermissionsRoute
  '/pos': typeof AppPosRoute
  '/prescriptions': typeof AppPrescriptionsRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/sign-in': typeof AuthSignInRoute
  '/customers/blacklist': typeof AppCustomersBlacklistRoute
  '/customers/new': typeof AppCustomersNewRoute
  '/products/new': typeof AppProductsNewRoute
  '/suppliers/new': typeof AppSuppliersNewRoute
  '/customers': typeof AppCustomersIndexRoute
  '/products': typeof AppProductsIndexRoute
  '/suppliers': typeof AppSuppliersIndexRoute
  '/products/$productId/edit': typeof AppProductsProductIdEditRoute
  '/suppliers/$supplierId/edit': typeof AppSuppliersSupplierIdEditRoute
  '/products/$productId': typeof AppProductsProductIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/expiry-tracker': typeof AppExpiryTrackerRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/permissions': typeof AppPermissionsRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/prescriptions': typeof AppPrescriptionsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/staff': typeof AppStaffRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_app/customers/blacklist': typeof AppCustomersBlacklistRoute
  '/_app/customers/new': typeof AppCustomersNewRoute
  '/_app/products/new': typeof AppProductsNewRoute
  '/_app/suppliers/new': typeof AppSuppliersNewRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
  '/_app/suppliers/': typeof AppSuppliersIndexRoute
  '/_app/products/$productId/edit': typeof AppProductsProductIdEditRoute
  '/_app/suppliers/$supplierId/edit': typeof AppSuppliersSupplierIdEditRoute
  '/_app/products/$productId/': typeof AppProductsProductIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/expiry-tracker'
    | '/inventory'
    | '/permissions'
    | '/pos'
    | '/prescriptions'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/staff'
    | '/sign-in'
    | '/customers/blacklist'
    | '/customers/new'
    | '/products/new'
    | '/suppliers/new'
    | '/customers/'
    | '/products/'
    | '/suppliers/'
    | '/products/$productId/edit'
    | '/suppliers/$supplierId/edit'
    | '/products/$productId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/expiry-tracker'
    | '/inventory'
    | '/permissions'
    | '/pos'
    | '/prescriptions'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/staff'
    | '/sign-in'
    | '/customers/blacklist'
    | '/customers/new'
    | '/products/new'
    | '/suppliers/new'
    | '/customers'
    | '/products'
    | '/suppliers'
    | '/products/$productId/edit'
    | '/suppliers/$supplierId/edit'
    | '/products/$productId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/dashboard'
    | '/_app/expiry-tracker'
    | '/_app/inventory'
    | '/_app/permissions'
    | '/_app/pos'
    | '/_app/prescriptions'
    | '/_app/reports'
    | '/_app/sales'
    | '/_app/settings'
    | '/_app/staff'
    | '/_auth/sign-in'
    | '/_app/customers/blacklist'
    | '/_app/customers/new'
    | '/_app/products/new'
    | '/_app/suppliers/new'
    | '/_app/customers/'
    | '/_app/products/'
    | '/_app/suppliers/'
    | '/_app/products/$productId/edit'
    | '/_app/suppliers/$supplierId/edit'
    | '/_app/products/$productId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/expiry-tracker': {
      id: '/_app/expiry-tracker'
      path: '/expiry-tracker'
      fullPath: '/expiry-tracker'
      preLoaderRoute: typeof AppExpiryTrackerRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/permissions': {
      id: '/_app/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AppPermissionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/prescriptions': {
      id: '/_app/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof AppPrescriptionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/customers/blacklist': {
      id: '/_app/customers/blacklist'
      path: '/customers/blacklist'
      fullPath: '/customers/blacklist'
      preLoaderRoute: typeof AppCustomersBlacklistRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/customers/new': {
      id: '/_app/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AppCustomersNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/products/new': {
      id: '/_app/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AppProductsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/suppliers/': {
      id: '/_app/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AppSuppliersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/suppliers/new': {
      id: '/_app/suppliers/new'
      path: '/suppliers/new'
      fullPath: '/suppliers/new'
      preLoaderRoute: typeof AppSuppliersNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/products/$productId/': {
      id: '/_app/products/$productId/'
      path: '/products/$productId'
      fullPath: '/products/$productId/'
      preLoaderRoute: typeof AppProductsProductIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/products/$productId/edit': {
      id: '/_app/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/products/$productId/edit'
      preLoaderRoute: typeof AppProductsProductIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/suppliers/$supplierId/edit': {
      id: '/_app/suppliers/$supplierId/edit'
      path: '/suppliers/$supplierId/edit'
      fullPath: '/suppliers/$supplierId/edit'
      preLoaderRoute: typeof AppSuppliersSupplierIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppExpiryTrackerRoute: typeof AppExpiryTrackerRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppPermissionsRoute: typeof AppPermissionsRoute
  AppPosRoute: typeof AppPosRoute
  AppPrescriptionsRoute: typeof AppPrescriptionsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppCustomersBlacklistRoute: typeof AppCustomersBlacklistRoute
  AppCustomersNewRoute: typeof AppCustomersNewRoute
  AppProductsNewRoute: typeof AppProductsNewRoute
  AppSuppliersNewRoute: typeof AppSuppliersNewRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
  AppSuppliersIndexRoute: typeof AppSuppliersIndexRoute
  AppProductsProductIdEditRoute: typeof AppProductsProductIdEditRoute
  AppSuppliersSupplierIdEditRoute: typeof AppSuppliersSupplierIdEditRoute
  AppProductsProductIdIndexRoute: typeof AppProductsProductIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppExpiryTrackerRoute: AppExpiryTrackerRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppPermissionsRoute: AppPermissionsRoute,
  AppPosRoute: AppPosRoute,
  AppPrescriptionsRoute: AppPrescriptionsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalesRoute: AppSalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStaffRoute: AppStaffRoute,
  AppCustomersBlacklistRoute: AppCustomersBlacklistRoute,
  AppCustomersNewRoute: AppCustomersNewRoute,
  AppProductsNewRoute: AppProductsNewRoute,
  AppSuppliersNewRoute: AppSuppliersNewRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
  AppSuppliersIndexRoute: AppSuppliersIndexRoute,
  AppProductsProductIdEditRoute: AppProductsProductIdEditRoute,
  AppSuppliersSupplierIdEditRoute: AppSuppliersSupplierIdEditRoute,
  AppProductsProductIdIndexRoute: AppProductsProductIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
